// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecflowTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GetFullyOccupiedDatesFeature : Xunit.IClassFixture<GetFullyOccupiedDatesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetFullyOccupiedDates.feature"
#line hidden
        
        public GetFullyOccupiedDatesFeature(GetFullyOccupiedDatesFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GetFullyOccupiedDates", "\tIn order to see the occupied dates\r\n\tAs a customer\r\n\tI want to have a list of th" +
                    "e dates that are occupied", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.TheoryAttribute(DisplayName="Get fully occupied dates")]
        [Xunit.TraitAttribute("FeatureTitle", "GetFullyOccupiedDates")]
        [Xunit.TraitAttribute("Description", "Get fully occupied dates")]
        [Xunit.InlineDataAttribute("\'12/9/2019\'", "\'12/10/2019\'", "0", new string[0])]
        [Xunit.InlineDataAttribute("\'12/19/2019\'", "\'12/19/2019\'", "1", new string[0])]
        [Xunit.InlineDataAttribute("\'12/17/2019\'", "\'12/22/2019\'", "3", new string[0])]
        [Xunit.InlineDataAttribute("\'12/21/2019\'", "\'12/24/2019\'", "1", new string[0])]
        [Xunit.InlineDataAttribute("\'12/22/2019\'", "\'12/23/2019\'", "0", new string[0])]
        public virtual void GetFullyOccupiedDates(string startdate, string enddate, string outcome, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get fully occupied dates", null, exampleTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
 testRunner.Given(string.Format("I have typed {0} and {1}", startdate, enddate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.And("the room from \'12/19/2019\' to \'12/21/2019\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.When("I press buttonr", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.Then(string.Format("the resultus shokuld be \'{0}\'", outcome), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GetFullyOccupiedDatesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GetFullyOccupiedDatesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
